// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnjpbjffkwzclzrmuauc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuanBiamZma3d6Y2x6cm11YXVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNDEzMjAsImV4cCI6MjA2MDcxNzMyMH0.WioTcdkmMf2vivAoJIqQrgzRZXWxPQnIOt-AtN5T11g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);